AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.9
    Timeout: 10

Resources:

  FileTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: file_id
          AttributeType: S
      KeySchema:
        - AttributeName: file_id
          KeyType: HASH

  FileBucket:
    Type: AWS::S3::Bucket

  ProcessUploadedFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/process_uploaded_file/
      Handler: app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref FileTable
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref FileBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref FileTable
